name: Repo parse
inputs:
  url:
    description: Repository url
    required: true
outputs:
  url:
    description: Repository url (rebuilt from vars)
    value: ${{ steps.repo.outputs.url }}
  repo:
    description: Repository
    value: ${{ steps.repo.outputs.repo }}
  domain:
    description: Repository service domain name
    value: ${{ steps.repo.outputs.domain }}
  scheme:
    description: Service scheme (http/https)
    value: ${{ steps.repo.outputs.scheme }}
  tag:
    description: Repository tag
    value: ${{ steps.repo.outputs.tag }}
runs:
  using: composite
  steps:
#    - shell: bash
#      run: |
#          echo ${{github.workspace}} >> $GITHUB_PATH
#          echo ${{github.workspace}}/.github/actions/repo-parse >> $GITHUB_PATH
    - name: Parse repository URL
      shell: bash
      id: repo
      run: |
          pwd
          ls -la
          echo $PATH
          action.sh "${{ inputs.url }}"
