name: Repository address parser helper
inputs:
  url:
    description: Repository url
    required: false
outputs:
  url:
    description: Repository url (rebuilt from vars)
    value: ${{ steps.repo.outputs.url }}
  repo:
    description: Repository name
    value: ${{ steps.repo.outputs.repo }}
  domain:
    description: Repository service domain name
    value: ${{ steps.repo.outputs.domain }}
  scheme:
    description: Service scheme (http/https)
    value: ${{ steps.repo.outputs.scheme }}
  tag:
    description: Repository tag
    value: ${{ steps.repo.outputs.tag }}
runs:
  using: composite
  steps:
    - name: Parse repository URL
      shell: bash
      id: repo
      run: run.sh "${{ inputs.url }}"
#      run: ${{github.action_path}}/action.sh "${{ inputs.url }}"
