name: Repository address parser helper
inputs:
  url:
    description: Repository url
    required: false
  repo:
    description: Repository (owner/name)
    required: false
  domain:
    description: Repository service domain name
    required: false
  scheme:
    description: Service scheme (http/https)
    required: false
  tag:
    description: Repository tag
    required: false

outputs:
  url:
    description: Repository url (rebuilt from vars)
    value: ${{ steps.repo.outputs.url }}
  repo:
    description: Repository name
    value: ${{ steps.repo.outputs.repo }}
  domain:
    description: Repository service domain name
    value: ${{ steps.repo.outputs.domain }}
  scheme:
    description: Service scheme (http/https)
    value: ${{ steps.repo.outputs.scheme }}
  tag:
    description: Repository tag
    value: ${{ steps.repo.outputs.tag }}
runs:
  using: composite
  steps:
    - name: Parse repository URL
      shell: bash
      id: repo
      outputs:
        url:
          description: Repository url (rebuilt from vars)
        repo:
          description: Repository name
        domain:
          description: Repository service domain name
        scheme:
          description: Service scheme (http/https)
        tag:
          description: Repository tag
      env:
        REPO: ${{ inputs.repo }}
        DOMAIN: ${{ inputs.domain }}
        SCHEME: ${{ inputs.scheme }}
        TAG: ${{ inputs.tag }}
      run: ${{github.action_path}}/action.sh "${{ inputs.url }}" >> $GITHUB_OUTPUT
