name: Repo parse
inputs:
  url:
    description: Repository url
    required: true
outputs:
  url:
    description: Repository url
    value: ${{ steps.repo.outputs.url }}
  repo:
    description: Repository
    value: ${{ steps.repo.outputs.repo }}
  domain:
    description: Repository service domain name
    value: ${{ steps.repo.outputs.domain }}
  scheme:
    description: Service scheme (http/https)
    value: ${{ steps.repo.outputs.scheme }}
  tag:
    description: Repository tag
    value: ${{ steps.repo.outputs.tag }}
runs:
  using: composite
  steps:
    - shell: bash
      run: echo ${{github.workspace}} >> $GITHUB_PATH
    - name: Parse repository URL
      id: repo
      run: action.sh "${{ inputs.url }}"
      shell: bash
