
env:
  name: 'repo-parse'

#name: Test ${{ env.name }}
on:
  workflow_dispatch:
  push:
    branches:
      - main
  paths:
    - '**repo-parse**'
    - '**lib.sh'
    - '**lib.bash'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: a
        uses: ./.github/actions/repo-parse
        with:
          url: 'https://github.com/a/b'
      - run: |
          test "${{ steps.a.outputs.url }}" = "${{ steps.a.outputs.scheme }}${{ steps.a.outputs.domain }}/${{ steps.a.outputs.repo }}"
          test "${{ steps.a.outputs.url }}" = 'https://github.com/a/b'
          test "${{ steps.a.outputs.repo }}" = 'a/b'
